### ISSUE TITLE
requirements/production.txt - fake-factory renamed to Faker

### ISSUE THREAD

**Issue by drocpdp** [la9ran9e/pyshard#3]
`Traceback (most recent call last):
  File "pyshard_demo.py", line 3, in <module>
    from faker import Faker
  File "/Users/davideynon/Projects/virtualenvs/pyshard/lib/python3.8/site-packages/faker/__init__.py", line 7, in <module>
    raise ImportError(error)
ImportError: The ``fake-factory`` package is now called ``Faker``.
`
PR following shortly.

**Comment by drocpdp** [comment]
wrong project!!!
